version: 1.0.{build}
image: Visual Studio 2019

install:
  - cmd: choco install dotnet.script

build_script:
  - cmd: >-
      cd build

      refreshenv

      dotnet script build.csx

branches:
  only:
    - master

artifacts:
  - path: build\Artifacts\NuGet\*.nupkg
    name: NuGet Packages

test: off
environment:
  IS_SECURE_BUILDENVIRONMENT:
    secure: xYC5jpSucUdHr8YwfxWefw==
  GITHUB_REPO_TOKEN:
    secure: FSPXTPuTgFMaZA7DubJoX217SkWhFLN2BGqCCi4gBux967eFtwkhbrafm7ay8cP2
  NUGET_APIKEY:
    secure: JfKADiDMHJBIYRnlh56cqh0HCqCRmeI6XJtFfGSPUlvI0a1FusqyFL+UVhskSPDBiJBt9NaFz5C+/cWX0+/BLhYRkD/bOl3R+FGfYq+fJ0adlk31wx/1G2FHSNwPfa6U

